version: '3.8'

services:
  wordpress:
    image: wordpress:6.3
    container_name: wordpress
    restart: always
    ports:
      - "80:80"  
    environment:
      WORDPRESS_DB_HOST: "${DB_ENDPOINT}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"  
      TZ: "America/Sao_Paulo"  
    volumes:
      - /mnt/efs:/var/www/html  
    networks:
      - wp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  wp-network:
    driver: bridge

volumes:
  db_data:
