version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"  
    environment:
      WORDPRESS_DB_HOST: "${DB_ENDPOINT}"
      WORDPRESS_DB_USER: "admin"   
      WORDPRESS_DB_PASSWORD: "admin_password"  
      WORDPRESS_DB_NAME: "wordpress"    
    volumes:
      - /mnt/efs:/var/www/html  
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  db_data:

